settings:
  give-items-on-join: true
  clear-inventory-on-join: true

items:
  selector:
    material: NETHER_STAR
    amount: 1
    slot: 4
    prevent-move: true
    prevent-drop: true
    name: "&6Lobby &fSelector"
    lore:
      - "&7Click derecho para abrir"
      - "&fAbre el menú de red"
    glow: true
    unbreakable: true
    custom-model-data: 1001
    enchants:
      - "DURABILITY:1"
    commands:
      player:
        - "/zmenu open zmenu:network_menu"
      console: []

  spawn_item:
    material: ENDER_PEARL
    amount: 1
    slot: 0
    prevent-move: true
    prevent-drop: true
    name: "&aVolver al Spawn"
    lore:
      - "&7Click derecho para regresar"
    glow: false
    unbreakable: true
    sound:
      type: "entity.enderman.teleport"
      volume: 1.0
      pitch: 1.0
    commands:
      player:
        - "/lobby spawn"
      console: []

  visibility_on:
    material: LIME_DYE
    amount: 1
    slot: 8
    prevent-move: true
    prevent-drop: true
    give-on-join: false
    name: "&aVer jugadores"
    lore:
      - "&7Click derecho para ocultarlos"
    glow: false
    unbreakable: true
    toggle-to: "visibility_off"
    commands:
      player:
        - "/lobby players hide"
      console: []

  visibility_off:
    material: GRAY_DYE
    amount: 1
    slot: 8
    prevent-move: true
    prevent-drop: true
    give-on-join: false
    name: "&7Ocultar jugadores"
    lore:
      - "&7Click derecho para mostrarlos"
    glow: false
    unbreakable: true
    toggle-to: "visibility_on"
    commands:
      player:
        - "/lobby players show"
      console: []

cycles:
  lobby_cycle:
    enabled: true
    slot: 0
    interval-ms: 1000
    items:
      - selector
      - spawn_item